Repository GMOD/jbrowse, pull requests merged in 2018-03, with the labels that each got.

#1013 Fix volvox track coloring
  docs/tutorial/conf_files/volvox.json
Labels: bug

#1018 Fix hidetracklabels when nav is gone
  plugins/HideTrackLabels/js/main.js
Labels: in progress

#870 Add removeCollapsedClick and removeCollapsedMouseover options
  docs/tutorial/data_files/functions.conf
  docs/tutorial/data_files/volvox_segment.bed
  release-notes.txt
  setup.sh
  src/JBrowse/View/Track/CanvasFeatures.js
  tests/selenium_tests/volvox_biodb_test.py
Labels: bug, feature req, in progress

#971 Moving labels canvasfeatures
  release-notes.txt
  src/JBrowse/View/FeatureGlyph/Box.js
  src/JBrowse/View/Track/CanvasFeatures.js
Labels: in progress

#900 Add support to index names for gff tabix (#780)
  src/perl5/Bio/JBrowse/Cmd/IndexNames.pm
Labels: feature req, needs review

#991 Add more gVCF support
  docs/tutorial/data_files/gvcf.vcf.gz
  docs/tutorial/data_files/gvcf.vcf.gz.conf
  docs/tutorial/data_files/gvcf.vcf.gz.tbi
  package.json
  release-notes.txt
  setup.sh
  src/JBrowse/Store/SeqFeature/VCFTabix/Parser.js
  src/JBrowse/View/Track/_VariantDetailMixin.js
  tests/data/raw.g.vcf.gz
  tests/data/raw.g.vcf.gz.tbi
  tests/data/raw.g.vcf.idx
  tests/js_tests/spec/VCF.spec.js
Labels: in progress
