Repository GMOD/jbrowse, pull requests merged in 2018-02, with the labels that each got.

#781 Add fix for bug that allows two instances of track to appear at startup
  release-notes.txt
  src/JBrowse/Browser.js
  src/JBrowse/GenomeView.js
Labels: bug, in progress, needs review

#985 Fix NeatCanvasFeatures - restore gradients
  plugins/CategoryUrl/README.md
  plugins/NeatCanvasFeatures/README.md
  plugins/NeatCanvasFeatures/img/example.png
  plugins/NeatCanvasFeatures/js/main.js
  plugins/NeatHTMLFeatures/README.md
  plugins/NeatHTMLFeatures/img/example.png
Labels: in progress

#917 upgrade google analytics to analytics.js and add optional parameter to record pageviews for one or more non-JBrowse Analytics users
  release-notes.txt
  src/JBrowse/Browser.js
Labels: in progress

#999 Update to bigwig for modencode tracks
  sample_data/json/modencode/trackList.json
Labels: in progress

#998 NPM module is located at @gmod/jbrowse
  utils/jb_run.js
  utils/jb_setup.js
Labels: in progress

#990 Use specific handling of no-call in variant detail
  docs/tutorial/data_files/volvox.test.vcf.gz
  docs/tutorial/data_files/volvox.test.vcf.gz.tbi
  release-notes.txt
  src/JBrowse/View/Track/_VariantDetailMixin.js
Labels: in progress

#1001 go to search completion immediately on click
  release-notes.txt
  src/JBrowse/Browser.js
Labels: feature req, in progress

#951 SNPCoverage: Exposed params for user customisation
  src/JBrowse/View/Track/SNPCoverage.js
Labels: feature req, small task

#885 Add workaround for when description is modified
  docs/tutorial/conf_files/volvox.json
  docs/tutorial/data_files/volvox.gff3
  release-notes.txt
  src/JBrowse/View/Track/_FeatureDetailMixin.js
Labels: feature req, in progress, needs review

#1007 ref sequence order enhancements
  bin/prepare-refseqs.pl
  release-notes.txt
  sample_data/raw/random_contigs.fa
  src/JBrowse/Browser.js
  src/perl5/Bio/JBrowse/Cmd/FormatSequences.pm
  tests/data/random_contigs_formatted_refseqs/seq/4c4/04e/7c/ctg12344-0.txt
  tests/data/random_contigs_formatted_refseqs/seq/8e5/250/ac/ctg232-0.txt
  tests/data/random_contigs_formatted_refseqs/seq/af2/43d/7e/ctg34532223-0.txt
  tests/data/random_contigs_formatted_refseqs/seq/efb/e96/28/ctg343453-0.txt
  tests/data/random_contigs_formatted_refseqs/seq/refSeqs.json
  tests/data/random_contigs_formatted_refseqs/trackList.json
  tests/data/random_contigs_formatted_refseqs/tracks.conf
  tests/perl_tests/prepare-refseqs.pl.t
Labels: feature req, in progress

#1008 Add "loading screen"
  index.html
  release-notes.txt
Labels: in progress

#1010 make subfeaturelevel default to 2
  css/main.css
  release-notes.txt
  src/JBrowse/View/Track/BlockBased.js
  src/JBrowse/View/Track/_FeatureDetailMixin.js
Labels: in progress

#847 Handle large structural variants in VCF better
  release-notes.txt
  src/JBrowse/Store/SeqFeature/VCFTabix.js
  src/JBrowse/Store/SeqFeature/VCFTabix/LazyFeature.js
  src/JBrowse/Store/SeqFeature/VCFTabix/Parser.js
  src/JBrowse/View/Track/_VariantDetailMixin.js
  tests/data/vcf.end.gz
  tests/data/vcf.end.gz.tbi
  tests/js_tests/index.html
  tests/js_tests/spec/VCF.spec.js
Labels: high priority, in progress

#1002 Delete git directory of built plugins
  build/Makefile
Labels: in progress

#986 Alignments2 mate highlight fix
  release-notes.txt
  src/JBrowse/Store/SeqFeature/BAM/LazyFeature.js
Labels: in progress
